### ISSUE TITLE
Add building and fmt on travis

### ISSUE THREAD

**Issue by TeXitoi** [stm32-rs/stm32f1xx-hal#1]
To check that we compile on a set of different rust version, and that our formating is consistent, I propose to check on travis that the crate and its examples are building, and that our formating comply with rustfmt.

If it's OK, I can propose a PR for that.

**Comment by therealprof** [comment]
@TeXitoi We will definitely have Travis CI (as we do for the other -hal crates in this organisation). It's not in at the moment due to the USB SNAFU which means it does not fully compile yet.

**Comment by TeXitoi** [comment]
I don't get it, right now, Cargo.toml point to japaric's stm32f103xx crate, so it should compile, no?

**Comment by TeXitoi** [comment]
@therealprof can you add an issue about this SNAFU problem with some explanations to be able to follow the works on this subject? Thanks.

**Comment by therealprof** [comment]
@TeXitoi Please find it in #3 .

**Comment by TeXitoi** [comment]
@therealprof thanks

**Comment by therealprof** [comment]
@TeXitoi You're now a collaborator on this crate (I hope).

**Comment by TeXitoi** [comment]
Yes, thanks to @adamgreig for the invitation on stm32-rs  org!

**Comment by therealprof** [comment]
> I don't get it, right now, Cargo.toml point to japaric's stm32f103xx crate, so it should compile, no?

That's just a dev dependency and shouldn't even be there...

**Comment by TheZoq2** [comment]
I think this can be closed now thanks to #208 and #207
