### ISSUE TITLE
Document the features = [stm32f103] requirement

### ISSUE THREAD

**Issue by TheZoq2** [stm32-rs/stm32f1xx-hal#11]
Given that the old stm32f103_hal crate is now deprecated, I figured I should update my projects. The first hurdle I ran into was  a couple of `unresolved import stm32` errors as well as `duplicate definitions with name <name>` errors. I managed to fix this once I figured out that you need to add a feature to specify which device you are compiling for.

However, this certainly wasn't obvious so it would be nice if it was added to the readme.

**Comment by therealprof** [comment]
Absolutely! Please feel free to send a PR. I'm also looking for people who're willing to share maintainership of this crate...

**Comment by TheZoq2** [comment]
> Absolutely! Please feel free to send a PR.
Done, #12 

> I'm also looking for people who're willing to share maintainership of this crate...

I wouldn't mind helping maintain this :)
