### ISSUE TITLE
PWM on TIM1 outputs

### ISSUE THREAD

**Issue by katyo** [stm32-rs/stm32f1xx-hal#119]
What the reason that *advanced timer* (TIM1) cannot be configured for PWM output like a *general purpose timers*?
I know that it require little bit an extra configuration for advanced features but in basics *advanced* timer may operate like *general purpose* timers.

**Comment by TeXitoi** [comment]
Because that's not yet implemented.

**Comment by burrbull** [comment]
Fixed by #147
