### ISSUE TITLE
spurious character in file src/i2c.rs

### ISSUE THREAD

**Issue by pdgilbert** [stm32-rs/stm32f1xx-hal#122]
There is an error using
cargo generate --name stm32f1xx-hal --git https://github.com/stm32-rs/stm32f1xx-hal

     let sr1 = $i2c.sr1.read();
Error: liquid:    --> 194:9
    |
194 |         let sr1 = $i2c.sr1.read();\u240a
    |         ^---
    |
    = expected Literal

This line seems to be in the file src/i2c.rs.  It has an (almost) invisible \u240a character at the end.

**Comment by therealprof** [comment]
Hm, weird. I just checked and there's nothing in the current git master.

**Comment by pdgilbert** [comment]
I assumed the character was the cause of the error  reported by 'cargo generate', but it may be that the character is format wrapper added by cargo generate when reporting another error. (It seems the character is neither in a git checkout nor in the file generated by cargo generate.)
Also, I cannot generate the error with cargo build or cargo check.

So I should not have assumed the cause,  the issue really is that  'cargo generate' gives
 Error: liquid: --> 194:9
|
194 | let sr1 = $i2c.sr1.read();\u240a  
 | ^---
|
= expected Literal

**Comment by burrbull** [comment]
`cargo generate` require specially formed (binary) repository. `stm32f1xx-hal` is library.

https://github.com/TeXitoi/blue-pill-quickstart/issues/7

**Comment by TheZoq2** [comment]
I guess that explains that. Kind of weird behaviour in my opinion, but I guess that's the fault of `cargo generate`
