### ISSUE TITLE
Where does crate::pac live?

### ISSUE THREAD

**Issue by smedellin90** [stm32-rs/stm32f1xx-hal#197]
I was looking at how the rtc is initialized for this stm32f1 family, and I noticed the following:
https://github.com/stm32-rs/stm32f1xx-hal/blob/37d1a7b3ec7d8a7edf5e1a178d8fd2863a4a578f/src/rtc.rs#L15

I'm new to rust, but I know that `use crate` refers to the current crate. But when I look for the module **pac** in the repository, it is nowhere to be found. Where is the source code for pac?

**Comment by thalesfragoso** [comment]
It's a re-export with alias, see here:
https://github.com/stm32-rs/stm32f1xx-hal/blob/37d1a7b3ec7d8a7edf5e1a178d8fd2863a4a578f/src/lib.rs#L83-L99

**Comment by smedellin90** [comment]
I see! Thank you for the explanation, @thalesfragoso

**Comment by smedellin90** [comment]
Are the pac module and stm32 module the same? I'm looking through the stm32f3xx-hal repository, and they have have re-export aliased in a similar way, but instead of pac, they name the module stm32. 

Below is a screenshot of docs.rs for stm32f1xx-hal:

![image](https://user-images.githubusercontent.com/5498472/78631543-8955b100-7851-11ea-8400-10fd2627d948.png)

**Comment by thalesfragoso** [comment]
There are several alias, in this repo the `pac` is the preferred one, but others are kept for retro compatibility.

**Comment by smedellin90** [comment]
Awesome, thanks again!
