### ISSUE TITLE
BluePill pinout error (PB5 remap must be T3C2, not T2C2)

### ISSUE THREAD

**Issue by spam-receiver** [stm32-rs/stm32f1xx-hal#238]
[Blue Pill pinout.pdf](https://github.com/stm32-rs/stm32f1xx-hal/files/4833837/Blue.Pill.pinout.pdf)

![Blue Pill pinout (big)](https://user-images.githubusercontent.com/48826370/85796233-431e3880-b742-11ea-9450-27c6ad05c6a1.gif)

**Comment by TheZoq2** [comment]
I'm not sure I understand what the issue is here. Are you saying that PB5 should be mapped to Timer 3 channel 2? If so, that is the case, but you need to use the `Tim3PartialRemap`, i.e. you then also have to remap channels 1-4 as (PB4, PB5, PB0, PB1)

**Comment by spam-receiver** [comment]
I just make a correction in the pinout according to [manufacturer's datasheet](https://www.st.com/resource/en/datasheet/stm32f103c8.pdf).

**Comment by burrbull** [comment]
Can you make pull request with change you want? I still don't understand what is wrong.

**Comment by spam-receiver** [comment]
Simply change BluePillPinout.jpg to this correct variant:

![BluePillPinout](https://user-images.githubusercontent.com/48826370/86027475-6e9e6d00-ba39-11ea-9ffb-8cdfbd5c8f84.jpg)

**Comment by burrbull** [comment]
You make us think that code is incorrect.

**Comment by spam-receiver** [comment]
)))
