### ISSUE TITLE
Support for 9 databits for USART peripheral

### ISSUE THREAD

**Issue by plaes** [stm32-rs/stm32f1xx-hal#262]
Some STM32F1 devices (at least stm32f103) supports programmable data word lengths (8 or 9 bits) for USART peripheral:
```
Word length may be selected as being either 8 or 9 bits by programming the M bit in the
USART_CR1 register.
```

![image](https://user-images.githubusercontent.com/91895/93056103-9f736300-f674-11ea-96c5-2fd1cacca36e.png)

**Comment by therealprof** [comment]
Indeed, unfortunately there's no straight forward way to express non "multiple of 8 Bits" word sizes in Rust.
