### ISSUE TITLE
embedded-hal-alpha.4?

### ISSUE THREAD

**Issue by pdgilbert** [stm32-rs/stm32f1xx-hal#295]
Is there a branch or fork of stm32f1xx-hal that builds with embedded-hal-alpha.4? I would like to do some testing with a crate (rust-radio-sx127x) that has moved to that, and the spi setup has to also use that version or the traits don't work properly.

**Comment by TheZoq2** [comment]
As far as I'm aware, there is no such fork. The closest I know of is this PR which ports to alpha1 https://github.com/stm32-rs/stm32f1xx-hal/pull/251

**Comment by eldruin** [comment]
I can update #251 to `-alpha.4`

**Comment by pdgilbert** [comment]
That would be great. Thanks.

**Comment by eldruin** [comment]
I have adapted it in #296. Cheers!
