### ISSUE TITLE
I2C example

### ISSUE THREAD

**Issue by pozix604** [stm32-rs/stm32f1xx-hal#305]
There is no I2C example available in the examples folder. This would be a welcome addition for those attempting to learn how to use the STM32 and this crate at the same time.

**Comment by TheZoq2** [comment]
This is a somewhat known problem also discussed in #24. Looks like some progress has been made in that area, so I might try to add an example later today.

For now, you can also have a look at https://github.com/TheZoq2/weather/blob/master/rtic_hardware/src/main.rs#L190 which at least shows how to set up i2c and pass it to a driver crate
