### ISSUE TITLE
UARTs should not enable DMA by default

### ISSUE THREAD

**Issue by Windfisch** [stm32-rs/stm32f1xx-hal#334]
In https://github.com/stm32-rs/stm32f1xx-hal/blob/5d55f83528a1a4eebcc672201751a320d9be5854/src/serial.rs#L312, every U(S)ART enables the DMA transmit and receive bits (dmat and dmar) unconditionally when initializing the UART struct.

This interferes with other users of the DMA channels, and it appears to me that this should rather be done in `TransferPayload::start()/::stop()`: https://github.com/stm32-rs/stm32f1xx-hal/blob/5d55f83528a1a4eebcc672201751a320d9be5854/src/serial.rs#L530-L546), like in the SPI implementation https://github.com/stm32-rs/stm32f1xx-hal/blob/5d55f83528a1a4eebcc672201751a320d9be5854/src/spi.rs#L569-L586

Or did I overlook something here?

**Comment by TheZoq2** [comment]
That certainly looks like a bug, thanks for reporting it! I'll look into fixing it when I find the time

**Comment by burrbull** [comment]
I think `with_dma` and `split` are better places to move this. Not `start` and `stop` transfer.

**Comment by Windfisch** [comment]
thanks @burrbull, this is indeed correct; I've updated my UART-pull request and would update the SPI-PR when I got some feedback on this one.
Could you review it please :)?

**Comment by Windfisch** [comment]
Hm, I sort of dislike the name `split` for this function; do you think there's a strong reason to use that name? SPI does not have yet a `split` function that releases its DMA structs. I am considering calling that function differently, like `release`. What do you think?

**Comment by burrbull** [comment]
> Hm, I sort of dislike the name `split` for this function; do you think there's a strong reason to use that name? SPI does not have yet a `split` function that releases its DMA structs. I am considering calling that function differently, like `release`. What do you think?

I think this is good idea.

**Comment by Windfisch** [comment]
Do we have a policy when renaming functions or introducing other breaking changes?
- Do we just document them in the CHANGELOG?
- Do we offer the (deprecated) old function name along with the new name for some time until all users have notices and updated?
- Or do we just break compatibility?

**Comment by Windfisch** [comment]
done, I updated both PRs. I think they are ready to merge now, if review don't say otherwise. Thanks for the feedback! :)
