### ISSUE TITLE
`stm32f1xx_hal::pac::Interrupt: Nr` is not satisfied

### ISSUE THREAD

**Issue by zrz4066** [stm32-rs/stm32f1xx-hal#374]
I can't compile OK after updating  stm32f1xx-hal.How to solve the issue. Thanks.

![image](https://user-images.githubusercontent.com/16775484/142335287-1b2bea3e-f157-4c3c-92da-c48597cd8e0b.png)

the trait bound `stm32f1xx_hal::pac::Interrupt: Nr` is not satisfied
the trait `Nr` is not implemented for `stm32f1xx_hal::pac::Interrupt`rustcE0277
nvic.rs(125, 12): required by a bound in `nvic::<impl cortex_m::peripheral::NVIC>::unmask`
error: the trait bound `stm32f1xx_hal::pac::Interrupt: Nr` is not [satisfied]([url]([url](url)))
label: the trait `Nr` is not implemented for `stm32f1xx_hal::pac::Interrupt`
note: required by a bound in `nvic::<impl cortex_m::peripheral::NVIC>::unmask`
label: the trait `Nr` is not implemented for `stm32f1xx_hal::pac::Interrupt`

**Comment by burrbull** [comment]
Check `cortex-m` and `cortex-m-rt` version. Are they compatible with `stm32f1` 0.14?

**Comment by zrz4066** [comment]
Thanks。     
 I change  from 
                 cortex_m::peripheral::NVIC::unmask(stm32f1xx_hal::pac::Interrupt::USART1);
       to
                 pac::NVIC::unmask(stm32f1xx_hal::pac::Interrupt::USART1);
    It compile ok
![image](https://user-images.githubusercontent.com/16775484/142362478-025019d3-9aff-4539-ac05-77bc633c3305.png)
