### ISSUE TITLE
Several errors when following the README's blinky.rs example

### ISSUE THREAD

**Issue by aboarya** [stm32-rs/stm32f1xx-hal#405]
OS: Ubuntu 20.04

When following the README's blinky example, I am getting several errors.  Here are my steps in some detail:

1. installed opencd using `sudo apt install opencd`
2. installed `gdb-arm-none-eabi` using `sudo apt install gdb-arm-none-eabi`
3. ran `rustup target install thumbv7m-none-eabi`
4. ran `cargo init blinky` and updated the Cargo.toml with the dependencies listed 
5. added [memory.x](https://github.com/stm32-rs/stm32f1xx-hal/blob/HEAD/memory.x) to the root of the project
6. created a `.cargo` directory and added the [config](https://github.com/stm32-rs/stm32f1xx-hal/blob/HEAD/.cargo/config)
7. overwrote main.rs with [blinky.rs ](https://github.com/stm32-rs/stm32f1xx-hal/blob/master/examples/blinky.rs)
8. ran `cargo build`

However I am getting the following errors, some them make sense, like [1.HZ](https://github.com/stm32-rs/stm32f1xx-hal/blob/master/examples/blinky.rs#L42)! Why does an integer have a method?

```
$ cargo build
   Compiling blinky v0.1.0 (~/blue-pill/practice/blinky)
error[E0061]: this function takes 1 argument but 0 arguments were supplied
  --> src/main.rs:36:30
   |
36 |     let mut gpioc = dp.GPIOC.split();
   |                              ^^^^^- supplied 0 arguments
   |                              |
   |                              expected 1 argument
   |
note: associated function defined here
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/stm32f1xx-hal-0.6.1/src/gpio.rs:86:8
   |
86 |     fn split(self, apb2: &mut APB2) -> Self::Parts;
   |        ^^^^^

error[E0599]: no method named `Hz` found for type `{integer}` in the current scope
  --> src/main.rs:42:70
   |
42 |     let mut timer = Timer::syst(cp.SYST, &clocks).start_count_down(1.Hz());
   |                                                                      ^^ method not found in `{integer}`

error[E0599]: no method named `set_high` found for struct `PC13` in the current scope
  --> src/main.rs:47:13
   |
47 |         led.set_high();
   |             ^^^^^^^^ method not found in `PC13<Output<PushPull>>`
   |
  ::: ~/.cargo/registry/src/github.com-1ecc6299db9ec823/embedded-hal-0.2.7/src/digital/v2.rs:60:8
   |
60 |     fn set_high(&mut self) -> Result<(), Self::Error>;
   |        -------- the method is available for `PC13<Output<PushPull>>` here
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
12 | use embedded_hal::digital::v2::OutputPin;
   |

error[E0599]: no method named `set_low` found for struct `PC13` in the current scope
  --> src/main.rs:49:13
   |
49 |         led.set_low();
   |             ^^^^^^^ method not found in `PC13<Output<PushPull>>`
   |
  ::: ~/.cargo/registry/src/github.com-1ecc6299db9ec823/embedded-hal-0.2.7/src/digital/v2.rs:54:8
   |
54 |     fn set_low(&mut self) -> Result<(), Self::Error>;
   |        ------- the method is available for `PC13<Output<PushPull>>` here
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
12 | use embedded_hal::digital::v2::OutputPin;
   |

Some errors have detailed explanations: E0061, E0599.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `blinky` due to 4 previous errors
```

**Comment by burrbull** [comment]
Short answer is git master branch and released versions can have differences.

**Comment by aboarya** [comment]
@burrbull DOH! I can't believe I didn't think of that!!!  thanks very much...I will look at the released version and try again, then report back here

**Comment by burrbull** [comment]
It was night and I wrote it from phone.

If you have time for experiments, I'd ask you for help with testing of #404 where I've added some more features for timers.
You can use it by setting
```toml
stm32f1xx-hal = { git = "https://github.com/stm32-rs/stm32f1xx-hal" branch ="delay-syst-micro" }
```
instead of released version.
Especcially https://github.com/stm32-rs/stm32f1xx-hal/blob/delay-syst-micro/examples/delay-timer-blinky.rs

**Comment by burrbull** [comment]
Also we are using now [cargo embed](https://github.com/probe-rs/cargo-embed) now instead of `openocd` as it is much more easier.

**Comment by aboarya** [comment]
@burrbull sound good! My plan is as follows:

1. run the blinky example using the steps in the README from the release branch
2. rerun the blinky steps using [cargo embed](https://github.com/probe-rs/cargo-embed)
3. test out [#404](https://github.com/stm32-rs/stm32f1xx-hal/pull/404)

should be able to report back on all this by tomorrow

**Comment by aboarya** [comment]
I am closing this issue now.  For anyone looking for an exact reason:

The README on the main branch suggests using version `0.6.1` of this crate, and links to an example `blinky.rs` from the master branch which will only work with the latest care from master.  

I propose to update the README to point to [blinky.rs](https://github.com/stm32-rs/stm32f1xx-hal/blob/4bbff64ed47049adf1d665cde0056692fac4918c/examples/blinky.rs) from commit [https://github.com/stm32-rs/stm32f1xx-hal/commit/4bbff64ed47049adf1d665cde0056692fac4918c](https://github.com/stm32-rs/stm32f1xx-hal/tree/4bbff64ed47049adf1d665cde0056692fac4918c) used to tag the `0.6.1` release.
