### ISSUE TITLE
Calling timer.start with timer interrupts enabled triggers interrupt

### ISSUE THREAD

**Issue by TheZoq2** [stm32-rs/stm32f1xx-hal#41]
When calling `Timer::start`, we trigger an update to reload the prescaler https://github.com/stm32-rs/stm32f1xx-hal/blob/master/src/timer.rs#L154. This update event triggers an interrupt if interrupts are enabled.

This can be mitigated temporarily by calling `unlisten` before calling `start`, but that is easy to miss. We should probably do that inside start if interrupts are enabled, or find a way to load the prescaler without an update event.

**Comment by thalesfragoso** [comment]
You could make use of the URS bit in the CR1 register (i.e. only generate interrupt/DMA request on counter overflow/underflow). You could even let it set if you do not care for interrupts using the slave mode controller or via software through the UG bit.
