### ISSUE TITLE
delta time / millis() like functionality using SYST timer

### ISSUE THREAD

**Issue by 30350n** [stm32-rs/stm32f1xx-hal#423]
Is there any easy way to get a per loop iteration delta time, using the `SYST` timer?
I kinda thought it'd be as simple as creating the timer with something like this and then calling the `now` function and calculating the delta from that.
```rust
...
let timer = core.SYST.counter_us(&clocks);
...
let mut last_time = timer.now();
loop {
    ...
    let now = timer.now();
    let delta_time = (last_time - now).to_millis();
    last_time = now;
}
```

But that seems to have multiple issues:

1. the `now()` function always returns `0` (unless the timers start function is called)
2. if I start the timer, it ends up stopping as soon as it overflows
3. if the timer overflows, the `last_time - now` part panics, because it would overflow (for some reason there doesn't seem to be a `wrapping_sub` variant to do this either)

Is there any easy way to accomplish what I'm trying to do? Because the work I seemingly have to put in to do so and all the hurdles I'd have to jump make it feel incredibly hacky to me.

**Comment by burrbull** [comment]
Possibly monotonic timer could help you.
Implementation for SysTick you can find in https://docs.rs/systick-monotonic/1.0.0/systick_monotonic/struct.Systick.html
For TIM2, TIM5 in timer::monotonic under `rtic` feature.

**Comment by 30350n** [comment]
Thanks! That seems to work reasonably well. I don't *really* like that i have to use a `u64` to prevent the timer/my instants from overflowing and that I seemingly have to use another unsafe block to `reset()` the timer to make it work at all (for no apparent reason), but yeah...

Also, maybe thats just me, but I feel like i shouldn't need yet another crate to accomplish something that simple without much trouble, but atleast it works now ^^

**Comment by 30350n** [comment]
Thanks again, the normal `systick-monotonic` implementation seems to work well enough for now though.
Here's what I ended up with, for future reference:
```Rust
use systick_monotonic::Systick;
...

#[entry]
fn main -> ! {
    ...
    let mut timer = Systick::<1_000>::new(core.SYST, clocks.sysclk().raw());
    unsafe { timer.reset(); } // this is kinda annoying imo, but whatever

    let mut last_time = timer.now();
    loop {
        let now = timer.now();
        let delta_time = last_time - now;
        last_time = now;
        ...
    }
}
```
