### ISSUE TITLE
get_clk returning 0 during timer.start

### ISSUE THREAD

**Issue by etrombly** [stm32-rs/stm32f1xx-hal#44]
#34 introduced a new way to get the timer clock, it is working correctly during the init portion of an RTFM program, but when I change the frequency and call start in a SysTick interrupt it is returning 0. This worked correctly with the old method. Not sure what could be causing it.

**Comment by thalesfragoso** [comment]
Can you provide a sample code to reproduce this issue ?

**Comment by etrombly** [comment]
I think it was my fault, I wasn't initializing late resources in rtfm.
